#! /usr/bin/bash

read -p "Enter name of project: " name

# replace all instances of 'skeleton' in makefile with new name 
sed -i -e "s/skeleton/$name/g" skeleton.makefile

# replace skeleton in all filenames with user supplied string
for filename in skeleton*; do newname=`echo $filename | sed "s/skeleton/$name/g"`; mv $filename $newname; done
